server:
  port: 8887

github:
  client:
    id: ac35951e1e98850afe96
    secret: b2fce6ada00acff7f10ebe6b1c63eefde16b69c4
  redirect:
    uri: http://localhost:8877/callback
spring:
  datasource:
    url: jdbc:h2:E:\IdeaProjects\community\community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
